backend:
  name: git-gateway
  branch: main # Проверь: если твоя ветка называется master, замени main на master!

media_folder: "img/projects"
public_folder: "img/projects"

collections:
  - name: "projects"
    label: "Проекты"
    folder: "data/projects"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Название проекта", name: "title", widget: "string" }
      - { label: "Ссылка на страницу проекта", name: "link", widget: "string", default: "./project-page.html" }
      - { label: "Обложка проекта", name: "image", widget: "image" }
      - { label: "Краткое описание", name: "description", widget: "text", required: false }